### ISSUE TITLE
Developing Navbar

### ISSUE THREAD

**Issue by MoazamAli45** [MoazamAli45/Quiz-AppHactoberfest2024#10]
Navbar should have home and about link.

**Comment by siddharthgoel94** [comment]
Hi,
Can you please assign this issue to me

**Comment by MoazamAli45** [comment]
Navbar should be according to design. Assigned

**Comment by siddharthgoel94** [comment]
Thank You
Well by design you mean the existing theme of website?

**Comment by MoazamAli45** [comment]
Yes
