### ISSUE TITLE
Developing About Us

### ISSUE THREAD

**Issue by MoazamAli45** [MoazamAli45/Quiz-AppHactoberfest2024#11]
About Page should contain cards which have pics, name and github profile link of contributor getting data dynamically from assets/content.md file and images from assets/images.

**Comment by siddharthgoel94** [comment]
Hi @MoazamAli45 ,
I would like to work on this issue as well. Can you please assign it to me

**Comment by MoazamAli45** [comment]
Sure you can but read the description it should get data dynamically from md file

**Comment by siddharthgoel94** [comment]
Ok 👍
