### ISSUE TITLE
Adding contact link on home page and make navbar same on contact us page 

### ISSUE THREAD

**Issue by MoazamAli45** [MoazamAli45/Quiz-AppHactoberfest2024#16]

**Comment by moudgalya1223** [comment]
hello @MoazamAli45  can I work on this?

**Comment by MoazamAli45** [comment]
Sure also check the email Js functionality

**Comment by moudgalya1223** [comment]
sure @MoazamAli45  thansk

**Comment by moudgalya1223** [comment]
hello @MoazamAli45  created  a link thaks

**Comment by wrexrus** [comment]
It says Permission denied please check in

**Comment by Nazim9945** [comment]
I have raised PR pls check and review.
