### ISSUE TITLE
Dark/Light Mode Toggle for Improved User Accessibility

### ISSUE THREAD

**Issue by poshithNandyala** [MoazamAli45/Quiz-AppHactoberfest2024#22]
### Description

Currently, the quiz app has a single theme, which may not cater to all users' preferences. Implementing a toggle feature that allows users to switch between dark and light modes will improve accessibility and user experience. The mode preference should persist across sessions, so using local storage for storing the user’s theme preference is recommended.

I would like to request that this issue be assigned to me, as I am participating in Hacktoberfest and would like to contribute by implementing this feature.

**Comment by MoazamAli45** [comment]
Sure

**Comment by poshithNandyala** [comment]
Thank you for assigning the issue. I will complete it as soon as possible.

**Comment by MoazamAli45** [comment]
Sure
