### ISSUE TITLE
Adding Reset Functionality

### ISSUE THREAD

**Issue by MoazamAli45** [MoazamAli45/Quiz-AppHactoberfest2024#3]

**Comment by siddharthgoel94** [comment]
Hi @MoazamAli45! I would like to work on this issue. Can you please assign it to me?

**Comment by siddharthgoel94** [comment]
Also in the Reset functionality :
it is supposed to start the quiz again from Q1 
OR 
just deselect the current selection and continue with the same quiz?

**Comment by MoazamAli45** [comment]
This issue is resolved now if you want to contribute you can make a header with home and about page on about page there should be cards of all contributors that should take dynamic data from assets/content.md file and also take image thanks

**Comment by siddharthgoel94** [comment]
I can make the about page as required
But I am not able to see the assets directory in the repository
Can you please help me through it

**Comment by MoazamAli45** [comment]
I have added the contribution folder you can dynamically data from there
