### ISSUE TITLE
Improving User experience

### ISSUE THREAD

**Issue by Prudhvi-232** [MoazamAli45/Quiz-AppHactoberfest2024#36]
in your website submit button is left and the prev button is on right actually for better user experience the submit button should be on right and the prev button should on left .

i would like to work on this issue under Hacktoberfest'24

![Screenshot 2024-10-21 231335](https://github.com/user-attachments/assets/a0b88226-0d90-4566-bd2c-095e7e6dbff9)

after updating it would be look like this

![image](https://github.com/user-attachments/assets/156a6e25-4900-427a-9532-45b09a6445be)

**Comment by MoazamAli45** [comment]
Assigned
